server:
  port: 8081
spring:
  application:
    name: backstage
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  cloud:
    inetutils:
      timeout-seconds: 5

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.cloud.common.pojo

eureka:
  instance:
    instance-id: backstage1_8081
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://22110334-8p.iec2.iac:7002/eureka/
#      defaultZone: http://cloud1:7001/eureka/,http://cloud2:7002/eureka/
