server:
  port: 80
spring:
  application:
    name: front_7800
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'




