server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://22110334-8p.iec2.iac:7002/eureka/
spring:
  cloud:
    inetutils:
      timeout-seconds: 5
