server:
  port: 8070
spring:
  application:
    name: backstage
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    url: jdbc:mysql://localhost:3306/test?useUnicode=TRUE&characterEncoding=UTF-8&useSSL=FALSE&serverTimezone=GMT
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  cloud:
    inetutils:
      timeout-seconds: 5

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.cloud.common.pojo

eureka:
  instance:
    instance-id: backstage_8070
    prefer-ip-address: true
    # eureka client 端向 server 端发送心跳间隔。默认 30 秒
    lease-renewal-interval-in-seconds: 30
    # eureka server端接收心跳之间的间隔。默认 90 秒。超过间隔时间，则此 client 置为失效状态
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7101/eureka/

